name = "All the Mods 10"
author = "ATMTeam"
version = "4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07eb63decbbdf81f6786ea4bf9bb3f76d1f7f6028fd5fbfeb3c02f23328e08b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.191"
